name: 'meu_projeto_dbt'
version: '1.0.0'
config-version: 2

profile: 'AED_DBT'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  meu_projeto_dbt:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
    marketing:
      +materialized: table
      +schema: marketing

seeds:
  meu_projeto_dbt:
    +schema: seeds
    +quote_columns: false
