---
name: 'meu_projeto_dbt'
version: '1.0.0'
profile: 'AED_DBT'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  meu_projeto_dbt:
    staging:
      materialized: view
      +schema: staging
      +docs:
        node_color: '#c0c0c0'
        show: true

    raw:
      materialized: table
      +schema: raw
      +docs:
        node_color: '#c0c0c0'
        show: true


seeds:
  meu_projeto_dbt:
    +schema: seeds
    +quote_columns: false
