name: "🛠️ Melhorias e Refatoração"
description: "Sugira melhorias ou refatorações no código."
title: "[REFACTOR] Nome da melhoria"
labels: ["refactor"]
body:
  - type: markdown
    attributes:
      value: "### 🔍 O que deve ser melhorado?\nExplique qual parte do código precisa de melhoria e por quê."
  - type: textarea
    id: benefits
    attributes:
      label: "🎯 Benefícios da Melhorias"
      description: "Por que essa melhoria é importante?"
  - type: textarea
    id: code
    attributes:
      label: "📜 Código Atual (Se aplicável)"
      description: "Se possível, forneça um trecho do código atual."
  - type: textarea
    id: implementation
    attributes:
      label: "💡 Sugestão de Implementação"
      description: "Descreva como a melhoria pode ser implementada."
