WITH PRODUTO AS (
    SELECT
        ID_PRODUTO,
        DESCRICAO_PRODUTO,
        ID_CATEGORIA,
        PRECO_UNITARIO,
        QUANTIDADE_ESTOQUE
    FROM PUBLIC.TB_PRODUTO
)

SELECT *
FROM PRODUTO
