version: 2

models:
  - name: stg_tb_status
    description: "Tabela de status"
    columns:
      - name: id_status
        description: "Identificador único."
        data_type: int
        tests:
          - unique
          - not_null
      - name: descricao_status
        description: "Descrição do status."
        data_type: varchar
        tests:
          - not_null
    contracts:
      enforce: true
