---
version: 2

models:

  - name: stg_canais_venda
    description: "Tabela de Canais de Venda de cada Pedido"
    columns:
      - name: id_canal_venda
        description: "Identificador único."
        tests:
          - unique
          - not_null
      - name: descricao_canal_venda
        description: "Descrição do Canal de Venda."
        tests:
          - unique
          - not_null

  - name: stg_categoria
    description: "Tabela das Categorias dos Produtos"
    columns:
      - name: id_categoria
        description: "Identificador único."
        tests:
          - unique
          - not_null
      - name: descricao_categoria
        description: "Descrição da Categoria."
        tests:
          - unique
          - not_null

  - name: stg_cliente
    description: "Tabela com os Dados dos Clientes"
    columns:
      - name: id_cliente
        description: "Identificador único."
        tests:
          - unique
          - not_null
      - name: primeiro_nome
        description: "Primeiro nome do Cliente."
        tests:
          - not_null
      - name: sobrenome
        description: "Sobrenome do Cliente."
        tests:
          - not_null
      - name: id_genero
        description: "Identificador do Gênero do Cliente."
        tests:
          - not_null
